quarkus.oidc.auth-server-url=http://localhost:8080/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret
quarkus.oidc.authentication.enabled=true
quarkus.oidc.token.issuer=http://localhost:8080/realms/quarkus
quarkus.oidc.token.audience=backend-service
